name: gff3merge
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.3.0
  - bedtools=2.29.2
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - enum34=1.1.6
  - ftputil=3.2
  - genometools=1.2.1
  - gffread=0.11.7
  - idna=2.8
  - intel-openmp=2020.0
  - ipaddress=1.0.23
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.16.6
  - numpy-base=1.16.6
  - openssl=1.1.1g
  - pip=19.3.1
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=2.7.18
  - readline=8.0
  - requests=2.22.0
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.31.1
  - tk=8.6.8
  - unicodecsv=0.14.1
  - urllib3=1.25.7
  - wheel=0.33.6
  - xmltodict=0.9.2
  - xz=5.2.5
  - zlib=1.2.11